name = "GeneticBitArrays"
uuid = "5d6f8c34-7f74-4dab-a49b-48b3414fbfce"
authors = ["Justin Angevaare <justinangevaare@gmail.com>"]
version = "0.2.1"

[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "â‰¥ 1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
